### PR TITLE
Added Share and Download Buttons + Title to dl.php

### PR DESCRIPTION
**Pull request by Peda1996**
Added Share and Download Buttons + Title!

Preview (pls don't judge my testphoto xD):  
grafik

As in https://github.com/photobooth-app/photobooth-app/issues/314 Mentioned, Share Button and Download Button would be handy.

### CODE REVIEW

**Comment by WebfinityDesign** [comment]
Nice! Well done!

**Comment by mgineer85** [comment]
While I was hesisting to additionally mix html and css with the php I will merge this now.
Thank you!

**Comment by WebfinityDesign** [comment]
In what browser did you test this?
I get "Web share is not supported in your browser"
The download button does work.
I tested it in Firefox, Chrome en Brave

**Comment by mgineer85** [comment]
On chrome it works, but I don’t think the share button is actually useful today on desktops

**Comment by Peda1996** [comment]
I think the share button only works on mobile Browsers 😅

michael ***@***.***> schrieb am Fr., 12. Juli 2024, 17:22:

**Comment by WebfinityDesign** [comment]
Sorry, I was talking about Chrom, Firefox and Brave on my Android phone

**Comment by Peda1996** [comment]
It's working on my Chrome and Kiwi Browsers. But I cannot get it to work on
Firefox, but Firefox should have implemented this api tho.

Th3o ***@***.***> schrieb am Fr., 12. Juli 2024, 17:27:

**Pull request merged**
