### PR TITLE
Added possibility to copy via USB Stick / eg. copy on plugin

### PR DESCRIPTION
**Pull request by Peda1996**
My take on automatically copying Photobooth files to an external USB device.

### CODE REVIEW

**Comment by mgineer85** [comment]
Thank you for the patch!🎉
Unfortunately, some checks fail.
If you have time feel free to send update, otherwise I'll have a look later.

**Comment by mgineer85** [comment]
Hey, I found the implementation is Linux exclusive.
Right now I managed to keep the app working on windows and linux.
You know whether there is a library available that is functional on windows also?

**Comment by Peda1996** [comment]
Hmm, completely forgot, that this external lib only supports linux, maybe by using psutil, and utilize polling windows and linux support might work?

I will try out an alternative implementation later. Will let you know once its done.

**Comment by Peda1996** [comment]
Should now work on Windows as well. Please test it. 

It basically now checks every second if a new disk partition was attached or removed, and according to this updates an internal list. If any new partition was added, the photos are now copied on this newly added partition.

**Comment by mgineer85** [comment]
Thx for sending the pull request. I modified a bit and added at least some basic tests that does not involve hardware.

**Pull request merged**
