### PR TITLE
add option to hide/delete images of a collage

### PR DESCRIPTION
**Pull request by DominicWindisch**
I felt like the individual images of each collage were cluttering the gallery quite a bit. 

Here's an option to hide or even delete these individual images entirely.

### CODE REVIEW

**Comment by mgineer85** [comment]
There is a field in the mediaitem foreseen for this already but not yet implemented fully. Think it should be easy to add it that way.

**Comment by DominicWindisch** [comment]
> There is a field in the mediaitem foreseen for this already but not yet implemented fully. Think it should be easy to add it that way.

That makes sense for visibility. I guess processingservice should set the visibility flag (somewhere around [here](https://github.com/photobooth-app/photobooth-app/blob/51de53842b6eda1178cfbc4b7bde054c39ce741a/photobooth/services/processingservice.py#L208)) based on a user setting and the mediacollectionservice would then filter for it in [`db_get_images_as_dict`](https://github.com/photobooth-app/photobooth-app/blob/51de53842b6eda1178cfbc4b7bde054c39ce741a/photobooth/services/mediacollectionservice.py#L107)?

How would you approach deleting the collage images?

**Comment by mgineer85** [comment]
We could add a filter that checks for visibility in the mediacollectionservice.db_get_images and .db_get_images_as_dict.
This way they would appear nowhere.

Deleting is not possible in the gallery then, but for bulk delete you would use the admin backend there is the delete gallery function available. It just deletes all files in /media folder.

**Comment by DominicWindisch** [comment]
Alright, I'll rework the hiding accordingly. Sounds like the proper approach to me to have them hidden from the front end entirely.

Deleting them directly probably isn't necessary, I agree.

**Pull request closed without merging**
